"""add hashed_password to users

Revision ID: 876981a9cefc
Revises: 2b086f4a58cf
Create Date: 2025-05-25 09:59:12.139358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876981a9cefc'
down_revision: Union[str, None] = '2b086f4a58cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('positive', 'negative', 'neutral', 'requirement', name='issuetype'), nullable=False),
    sa.Column('agreement_level', sa.Enum('high', 'medium', 'low', name='agreementlevel'), nullable=True),
    sa.Column('classification', sa.Enum('agreed', 'discussing', 'disagreed', name='issueclassification'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.add_column('analyses', sa.Column('analysis_type', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('result', sa.Text(), nullable=True))
    op.create_index(op.f('ix_analyses_analysis_type'), 'analyses', ['analysis_type'], unique=False)
    op.drop_constraint('analyses_conversation_id_fkey', 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('analyses', 'emotion')
    op.drop_column('analyses', 'main_points')
    op.drop_column('analyses', 'keywords')
    op.add_column('conversations', sa.Column('content', sa.Text(), nullable=False))
    op.drop_constraint('conversations_project_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('conversations', 'transcript')
    op.drop_column('conversations', 'audio_url')
    op.add_column('projects', sa.Column('status', sa.String(), nullable=True))
    op.add_column('proposals', sa.Column('support_rate', sa.Float(), nullable=True))
    op.add_column('proposals', sa.Column('is_selected', sa.Boolean(), nullable=True))
    op.add_column('proposals', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('proposals_project_id_fkey', 'proposals', type_='foreignkey')
    op.create_foreign_key(None, 'proposals', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('proposals', 'image_url')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.add_column('proposals', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.create_foreign_key('proposals_project_id_fkey', 'proposals', 'projects', ['project_id'], ['id'])
    op.drop_column('proposals', 'updated_at')
    op.drop_column('proposals', 'is_selected')
    op.drop_column('proposals', 'support_rate')
    op.drop_column('projects', 'status')
    op.add_column('conversations', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_project_id_fkey', 'conversations', 'projects', ['project_id'], ['id'])
    op.drop_column('conversations', 'content')
    op.add_column('analyses', sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('analyses', sa.Column('main_points', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('analyses', sa.Column('emotion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.create_foreign_key('analyses_conversation_id_fkey', 'analyses', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('ix_analyses_analysis_type'), table_name='analyses')
    op.drop_column('analyses', 'result')
    op.drop_column('analyses', 'analysis_type')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
