"""add title column to agreement table

Revision ID: 92cca29726a9
Revises: 63694f32c2cb
Create Date: 2025-05-25 18:55:19.740306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cca29726a9'
down_revision: Union[str, None] = '63694f32c2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements', 'title')
    # ### end Alembic commands ###
