"""add_email_to_project_members

Revision ID: f59c7cc35778
Revises: 8121ade3f991
Create Date: 2025-06-20 19:41:59.938577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59c7cc35778'
down_revision: Union[str, None] = '8121ade3f991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'email')
    # ### end Alembic commands ###
